// Writes js/config.js from environment variables, falling back to .env.
// The browser can't read env vars, so this is the one build step the site has.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const REQUIRED = ["SUPABASE_URL", "SUPABASE_ANON_KEY"];

function readDotEnv(path) {
  if (!existsSync(path)) return {};
  const vars = {};
  for (const line of readFileSync(path, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match) vars[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }
  return vars;
}

const fileVars = readDotEnv(join(root, ".env"));
const config = Object.fromEntries(REQUIRED.map((name) => [name, process.env[name] || fileVars[name] || ""]));

const missing = REQUIRED.filter((name) => !config[name]);
if (missing.length) {
  console.error(`Missing ${missing.join(", ")}. Set them in .env or the host's environment variables.`);
  process.exit(1);
}

config.SUPABASE_URL = config.SUPABASE_URL.replace(/\/rest\/v1\/?$/, "").replace(/\/$/, "");

const body = REQUIRED.map((name) => `export const ${name} = ${JSON.stringify(config[name])};`).join("\n");
writeFileSync(join(root, "js", "config.js"), `// Generated by scripts/build-config.mjs — do not edit.\n${body}\n`);
console.log("Wrote js/config.js");
